# Generated by Django 3.2.17 on 2023-02-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_TYPE',
            fields=[
                ('typeID', models.IntegerField(primary_key=True, serialize=False)),
                ('typeUser', models.CharField(max_length=30)),
            ],
        ),
    ]
