# Generated by Django 3.2.17 on 2023-02-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEMBERSHIP_MASTER',
            fields=[
                ('membershipID', models.IntegerField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.CharField(max_length=100)),
                ('membershipStatus', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PLAN_MASTER',
            fields=[
                ('planID', models.IntegerField(primary_key=True, serialize=False)),
                ('planTitle', models.CharField(max_length=30)),
                ('planDetail', models.CharField(max_length=100)),
                ('planPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planDuration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCT_MASTER',
            fields=[
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('productImage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='USER_MASTER',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=80)),
                ('mobile', models.IntegerField()),
                ('idProof', models.CharField(max_length=100)),
                ('typeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_type')),
            ],
        ),
        migrations.CreateModel(
            name='WORKOUT_MASTER',
            fields=[
                ('workoutID', models.IntegerField(primary_key=True, serialize=False)),
                ('dietChart', models.CharField(max_length=50)),
                ('workoutSchedule', models.CharField(max_length=50)),
                ('videos', models.URLField()),
                ('rewards', models.CharField(max_length=20)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='TRAINER_DETAILS',
            fields=[
                ('trainerID', models.IntegerField(primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT_MASTER',
            fields=[
                ('paymentID', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(max_length=20)),
                ('transactionNumber', models.IntegerField()),
                ('paymentRecipt', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=10)),
                ('membershipID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.membership_master')),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_MASTER',
            fields=[
                ('orderID', models.IntegerField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('deliveryStatus', models.CharField(max_length=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='ORDER_DETAILS',
            fields=[
                ('detailsID', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total', models.FloatField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order_master')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product_master')),
            ],
        ),
        migrations.AddField(
            model_name='membership_master',
            name='planID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plan_master'),
        ),
        migrations.AddField(
            model_name='membership_master',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master'),
        ),
        migrations.CreateModel(
            name='FEEDBACK_MASTER',
            fields=[
                ('feedbackID', models.IntegerField(primary_key=True, serialize=False)),
                ('details', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master')),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_MASTER',
            fields=[
                ('attendanceID', models.IntegerField(primary_key=True, serialize=False)),
                ('attendanceDate', models.DateField()),
                ('timeIN', models.TimeField()),
                ('timeOUT', models.TimeField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user_master')),
            ],
        ),
    ]
