# Generated by Django 3.2.17 on 2023-02-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230208_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
